id: opecha:P008265
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25246
  title: དགེ་ལྡན་ཁྲི་ཐོག་རིམ་བྱོན་གྱི་རྣམ་ཐར་ལས། ཁྲི་ཐོག་དྲུག་ཅུ་རེ་བརྒྱད་དང་བདུན་ཅུ་ཐམ་པ་དང་བདུན་ཅུ་དོན་བཞི་བཅས་ཀྱི་རྣམ་ཐར།
  volume: ''
  author: ''
