id: ID766A859
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T08:26:05+00:00'
last_modified: '2022-06-08T08:20:33.510408+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25246
  title: དགེ་ལྡན་ཁྲི་ཐོག་རིམ་བྱོན་གྱི་རྣམ་ཐར་ལས། ཁྲི་ཐོག་དྲུག་ཅུ་རེ་བརྒྱད་དང་བདུན་ཅུ་ཐམ་པ་དང་བདུན་ཅུ་དོན་བཞི་བཅས་ཀྱི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    DCE7:
      image_group_id: I1KG25248
      title: ''
      total_pages: 255
      order: 1
      base_file: DCE7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
