id: ID766A859
legacy_id: P008265
ocr_import_info:
  bdrc_scan_id: W1KG25246
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T08:24:25'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T14:11:31.878709+00:00'
last_modified: 2022-08-31 22:11:42.348670
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG25246
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG25246
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དགེ་ལྡན་ཁྲི་ཐོག་རིམ་བྱོན་གྱི་རྣམ་ཐར་ལས། ཁྲི་ཐོག་དྲུག་ཅུ་རེ་བརྒྱད་དང་བདུན་ཅུ་ཐམ་པ་དང་བདུན་ཅུ་དོན་བཞི་བཅས་ཀྱི་རྣམ་ཐར།
  author: ཚེ་སྨོན་གླིང ༠༢་ངག་དབང་འཇམ་དཔལ་ཚུལ་ཁྲིམས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.8955882691292644
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG25248:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG25248
      total_pages: 255
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG25248.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8955882691292644
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
